### ISSUE TITLE
Original Miyoo Mini immediately shuts down after booting

### ISSUE THREAD

**Issue by Vexnik** [goweiwen/Allium#1]
I just installed Allium on my SD card, when it boots up it immediately shuts down.

**Comment by goweiwen** [comment]
Hi, Allium is not supported in the Miyoo Mini yet, as I do not own one. It will be in the future when I get my hands on on. Thank you.

**Comment by goweiwen** [comment]
I have just pushed a [new version (v0.5.1)](https://github.com/goweiwen/Allium/releases/tag/v0.5.1) that should fix the boot issues. However, you should expect these issues with the Miyoo Mini:
- Battery indicator not working
- Volume hotkey & brightness hotkeys currently use volume key, so cannot be used.

If you wish to test it, please let me know if there are any other issues. The logs can be found on the SD card at `.allium/alliumd.log`.

**Comment by Vexnik** [comment]
[alliumd.log](https://github.com/goweiwen/Allium/files/11832836/alliumd.log)

Finally boots on original Miyoo Mini, but I was unable to shut down, screen went black while the green led still on. Gotta unplug the battery to shut it down

**Comment by goweiwen** [comment]
Thanks for testing it out. I think I have to use a different command for shutting down (`reboot -r` instead of `poweroff`) on the MM. Let me get that in the next release.

**Comment by goweiwen** [comment]
Just released v0.8.0 which should fix the shutdown issue as well as add volume/brightness hotkeys (start/select + L2/R2).
