### ISSUE TITLE
Can this work alongside Onion?

### ISSUE THREAD

**Issue by dreams897** [goweiwen/Allium#16]
Sorry this is not an issue but a question as I don't know how this works. Can this be used alongside Onion OS or is it only a stand-alone replacement?

**Comment by goweiwen** [comment]
This is a standalone program that manages the hardware (volume, brightness etc) itself, so is not compatible with Onion.

It might be possible to allow launching Onion from within Allium with a simple app, but I don't have plans on implementing that now.
