### ISSUE TITLE
Screen doesn't turn off when charging (mm+)

### ISSUE THREAD

**Issue by h8uthemost** [goweiwen/Allium#19]
Hi guys,

You have an excellent firmware. But I've found an unfortunate bug. The screen doesn't shut off when I charge my Miyoo mini plus. Hopefully this is an easy fix..

Allium 0.20.8
Model # MY354
Firmware version: 202306282128

I believe that all the info. And it seems to be only Allium. The screen goes off on Onion and DotUI. Perhaps I'm not turning something on or off

Thanks for reading 

EDIT: Sorry I should have given more info. When using Onion or Dot, when my device is off and I plug it in to charge, the device goes only to the battery image then the screen goes dark again. When I have Allium, when I plug the device in to charge, it goes to the battery image but then right into Allium. Instead of going dark again. And then Allium just stays awake. I can move around into games and whatnot.

So I hope that's a little more clearer. I re-read what I first typed and thought I better edit it. Lol

EDIT AGAIN: It looks like I can simply power it off by the power button and it goes to black screen. The red light is on so I assume it's charging. 

Eventhough I'd like to have a proper Shutdown option, and for the screen not to turn on when I go to charge, I can live with just powering off the device. I'll let you know if it doesn't go to full charge with the power off.

**Comment by goweiwen** [comment]
Hey! Thanks for reporting this. This is a known issue and can be fixed.

**Comment by h8uthemost** [comment]
Ok just wanted to let you know. I can't figure out how to change cores for a particular game, but that's conversation for another thread. Lol

I'll keep my eye out for updates. Live your firmware 

Take care

**Comment by goweiwen** [comment]
You can choose a core by pressing select before launching the game. This should be more discoverable, thanks.

**Comment by Fireblend** [comment]
Still present in 0.21.0, would love to see this fixed!

**Comment by goweiwen** [comment]
Suspend is now implemented in v0.22.0. :slightly_smiling_face: 

When booting while charging, the device will automatically suspend. This also means you have to wake it up by pressing the power button once if you try to boot the device while charging.
