### ISSUE TITLE
MM+ enters a boot loop when trying to install

### ISSUE THREAD

**Issue by marvilarms** [goweiwen/Allium#2]
After setting up the SD card and inserting it for the first time for installation, the device enters a boot loop, turning on and off over and over.

**Comment by marvilarms** [comment]
Firmware is the latest (0609)

**Comment by goweiwen** [comment]
Thanks for testing this out. Which version are you on? Can you help to get the logs at `/mnt/SDCARD/.allium/alliumd.log`?

**Comment by marvilarms** [comment]
[alliumd.log](https://github.com/goweiwen/Allium/files/11790753/alliumd.log)

**Comment by goweiwen** [comment]
Allium expects a `Roms` folder at the root of your SD card where the games are stored. Do you have that?

**Comment by marvilarms** [comment]
No, I just formatted the SD card and extracted the contents of the zip file to the root. So I should just create a ROMS folder after extracting?

**Comment by goweiwen** [comment]
Yup, go ahead and create a `Roms` folder and put in some games. If your roms are zipped, they need to be in folders named after their console e.g. `Game Boy Advance (GBA)` or `GBA`. Following OnionOS's or DotUI's folder structure will work.

**Comment by goweiwen** [comment]
No problem! Feel free to let me know if you face any other issues.

**Comment by marvilarms** [comment]
If the zip file for Allium already containd the Roms folder or any other expected by the system, even if empty, would it suffice to boot the system?

**Comment by goweiwen** [comment]
Yes, I should set up the release to contain the Roms and BIOS folders as well. Thanks.
