### ISSUE TITLE
SSID pre-populated and password field had text on fresh install

### ISSUE THREAD

**Issue by maxengel** [goweiwen/Allium#20]
I did a clean install of Allium and, when going through my initial setup, the SSID of my home network and the password were already present. I’m wondering where this info was pulled from?

**Comment by nitrox710** [comment]
u can try with 2 sd cards, if u put onion on one for example and then shut down the console, it would keep those on the rom of the miyoo, then u put another card and the data would match with ssid and password.

**Comment by goweiwen** [comment]
This data is stored in the built-in flash memory of the Miyoo Mini, which is where stock OS and Onion OS writes to. On the first boot, Allium will try to read from it.
