### ISSUE TITLE
Save State Screenshots

### ISSUE THREAD

**Issue by cuteseal1** [goweiwen/Allium#23]
Hello and thank you for your awesome work on Allium.
I was wondering if it was on the roadmap to implement save state screenshots in the in-game menu? 
Similar to MinUI/MiniUI.  Instead of just showing the "Slot N" text, to show the actual screenshots of the save states as well.

Thank you!

**Comment by cuteseal1** [comment]
Thank you for all your great work!

**Comment by goweiwen** [comment]
Implemented in v0.23.0 5134bb3
