### ISSUE TITLE
Option to change charging animation & pop-up

### ISSUE THREAD

**Issue by Nordyx** [goweiwen/Allium#24]
Is there a method to modify animations, such as the charging animation? Or pop-up - like the shutdown window. 

In Onion OS, you can find it within sdcard/.tmp_update/res.

Edit: I forgot to mention that this is by far my favorite OS for the Miyoo Mini+. Exceptional work!

**Comment by goweiwen** [comment]
There is no such feature planned. I'll keep this in mind when implementing custom themes.

For now, you can modify the shut down text here: `.allium/locales/en-US/main.ftl`
https://github.com/goweiwen/Allium/blob/b25a272ab24cf9ef9cf96fdcda26eb1346f94658/assets/root/.allium/locales/en-US/main.ftl#L113
