### ISSUE TITLE
Going back from subfolders goes to top level

### ISSUE THREAD

**Issue by cuteseal1** [goweiwen/Allium#25]
Minor issue, but when browsing through games, and going into subfolders, pressing "B" to go back will move it back to the top level folder, instead of the previous level folder.

e.g.

1. Navigate to Games > Gameboy Advance > Translations (folder)
2. Press "B" to go back
3. Goes back to Games.  It should go to Gameboy Advance instead...

**Comment by goweiwen** [comment]
This will be fixed in the next release, thanks for reporting.
