### ISSUE TITLE
Is save/load hotkeys feature like Onion planned?

### ISSUE THREAD

**Issue by mtwtkman** [goweiwen/Allium#26]
OnionOs has save/load hotkeys feature on the other hand, Allium (v0.23.0) seems does not have one.
I can't find Allium's development roadmap, so I created this issue.

Even if it wasn't planned, I respect great product Allium develop team's decision. Thank you.

**Comment by cuteseal1** [comment]
I think you should be able to achieve this by going into retroarch settings for the time being.
i.e. Settings > Retroarch (Settings) > Hotkeys > Save State / Load State

That being said, I do prefer the Allium way of avoiding the use of hotkeys vs Onion, as it is more intuitive.
