### ISSUE TITLE
Best way to update 

### ISSUE THREAD

**Issue by h8uthemost** [goweiwen/Allium#32]
Hi Allium developers,

I'm here to ask the proper way to update Allium. On my v22 mm+ I thought just replacing the tmp_update folder with the v23 tmp_update folder would update Allium, but it didn't.

So I then replaced the .allium folder and the tmp_update folder. And that updated me from v22 to v23. But it seems I lost some settings doing it that way. It said "installed retroarch" when I did this. I thought I would get an "updating Allium" message instead. 

Me and a couple others have looked around for update instructions but haven't found any. So what's the proper way to update Allium?
Thanks devs

**Comment by goweiwen** [comment]
You should be able to update by extracting and merging the entire zip into your SD card root.

If you don't delete the `.allium` folder and just merge the folders, your settings should remain.

**Comment by h8uthemost** [comment]
Oh ok. So just unzip and drag n drop all 6(or is it 7) folders onto the sd card and let it overwrite everything on the sd? I'm guessing that's what you mean by merging the folders, overwrite them.

Well thank you for answering. Now I know how to do it properly.

**Comment by goweiwen** [comment]
Yes, that is right. :smile:

I will update the README to include update instructions, thank you.

**Comment by h8uthemost** [comment]
Lol. Ok, I was just making sure I was reading you correctly. And putting instructions in a readme would be perfect. 

Thanks for making the best cfw for the mm+ even better! I just wish it was available for other devices too. Like the rg35xx.
