### ISSUE TITLE
Update instructions -> caution for mac users

### ISSUE THREAD

**Issue by cuteseal1** [goweiwen/Allium#34]
Hi there, I saw that you have added Update instructions asking users to extract all and choose "Overwrite" if prompted.

I think this is fine for Windows users as it will do an "additive" copy, and overwrite files if they exist.
But for mac users if they choose "replace" instead of "merge" then they could potentially replace their BIOS, Saves and Roms folders with the empty ones from the allium zip file.

Suggest updating the instructions to only copy the .allium, .tmp_update, Apps and RetroArch folders.

**Comment by goweiwen** [comment]
Thanks, hopefully no one has replaced their important folders yet!
