### ISSUE TITLE
Suggestion: Exclude .sbi files from PS gamelist.

### ISSUE THREAD

**Issue by Oberworld** [goweiwen/Allium#35]
Some Pal psx games like Dino Crisis or Ape Scape need an sbi file along with the game image to work. This file has the same name as the game.

In psx gamelist you can see the name of the game twice for the games that use this file.

It would be great if these files were excluded from the psx games list.

More info about .sbi files: https://psxdatacenter.com/sbifiles.html

Regards.

**Comment by goweiwen** [comment]
Thanks, I wasn't aware of this.
