### ISSUE TITLE
Suggestion: sort consoles by displayed name

### ISSUE THREAD

**Issue by Oberworld** [goweiwen/Allium#37]
If you use onion folder structure, you obtain a list like this order:

Commodore 64
Amstrad CPC
Famicom Disk
Atari 5200

Even if you select order: A to Z.

Sorry for so many requests, I try to contribute with translations and other fixes, i'm not a programmer.

**Comment by goweiwen** [comment]
Thanks, I missed this one.

**Comment by goweiwen** [comment]
Don't worry about the requests! I sometimes miss some things that don't affect me so it's good that users can help to report such issues.
