### ISSUE TITLE
Suggestion: Implement FFplay.pak in Apps folder

### ISSUE THREAD

**Issue by lemonlimelabs** [goweiwen/Allium#39]
It would be great if Allium could include FFplay in its standard apps for viewing videos like OnionOS does. I tried to make it work on my own but did not succeed.

Keep up the great work. Allium is my favorite way to experience the Miyoo Mini!

**Comment by goweiwen** [comment]
That sounds good. I believe the one OnionOS includes uses some tools that come packaged with OnionOS, like `shellect`, which lets you select which video to play. When I add FFplay, I want to add a proper GUI to select the videos so the user can view the thumbnails before launching.

I could also hook FFplay up as a launcher for the file types that it supports, so you can have the videos in a folder in your Roms directory and just launch to watch them. I'll probably still add an FFplay app if I do it this way, though.

**Comment by Oberworld** [comment]
I've found this one that doesn't use swap memory and doesn't use parasyte library but can't make it work.

https://github.com/bobotrax/ffplay_Miyoo/releases

I have the file selector shellect working, it's so easy, but videos doesn't launch.

**Comment by goweiwen** [comment]
This is now implemented in fde5c3d6c5967f3657f98a6cf93cc2fb18e283c3. It is implemented as a core, so you have to add your media files in the Roms directory.

e.g.
>Roms/Videos (MEDIA)/Episode 1.mp4
>Roms/Movies/Episode 1.mp4
