### ISSUE TITLE
Games with multiple files are being shown as multiple entries

### ISSUE THREAD

**Issue by Sneheth** [goweiwen/Allium#49]
The games having multiple files such as PS1 games which may have multiple .bin and a .cue files are being shown as multiple entries in the “Games” section.
![2023-12-22_04-29-54-Allium](https://github.com/goweiwen/Allium/assets/37405162/05289231-d107-49c3-acee-3879dd94f761)
![IMG_0039](https://github.com/goweiwen/Allium/assets/37405162/961dd558-9f0f-484a-b1bb-39b0220dd18b)

**Comment by Sneheth** [comment]
It is better to just show names of .cue files in this cases

**Comment by goweiwen** [comment]
Implemented in d0d029a, thanks.
