### ISSUE TITLE
What sort of box art do you support?

### ISSUE THREAD

**Issue by josegonzalez** [goweiwen/Allium#5]
I was wondering if you support all three box arts from the following repo (and in particular the full screen mix option).

https://github.com/ebzero/garlic-onion-skraper-mix

Regardless, so you have some documentation on how to add box art?

**Comment by goweiwen** [comment]
Aside from the image width being 250px in Allium, you can follow those instructions and it should work. Allium looks into the `Imgs` folder first to be compatible with stock/OnionOS.

**Comment by josegonzalez** [comment]
What is the image height in Allium?

**Comment by goweiwen** [comment]
The UI is dynamic based on the font size used, so it depends. I don't have a number off the top of my head for the default font size.

If the image is too tall, it will be scaled down to fit within the boundaries (i.e. [CSS's contain](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)).
