### ISSUE TITLE
Games with multiple files are being shown as multiple entries

### ISSUE THREAD

**Issue by Sneheth** [goweiwen/Allium#54]
As mentioned in the issue #49, the games are still being shown as multiple entries, although not as many as in previous version. I have repopulated the database multiple times and the result is the same. These are the files that I have and the entries that are being shown for your reference.
![2023-12-30_18-26-52-Allium](https://github.com/goweiwen/Allium/assets/37405162/27d8de2d-0a69-4dc5-90da-bcecbda4a4f2)
![2023-12-30_18-27-12-Allium](https://github.com/goweiwen/Allium/assets/37405162/898a0e26-cf72-41ac-8f85-13fdf2402598)

**Comment by goweiwen** [comment]
I think these games exist in the database with some playtime, so they will not be removed when repopulating the DB to preserve the data.

You should be able to remove these entries by pressing select over them and selecting "Remove from Recents". The first entry should be the .cue, and everything else should be the .bins.

**Comment by Sneheth** [comment]
I tried removing them from recents and it worked. Thank you for your awesome work for the Miyoo community. This is my daily driver now.
