### ISSUE TITLE
Suggestion for the Guide feature 

### ISSUE THREAD

**Issue by h8uthemost** [goweiwen/Allium#56]
Hey Allium devs,

I was wondering if it would be at all possible to move the Guide option in the In-game Menu up right underneath the Continue option (to continue your game). 

The reason I'm asking is because I'm playing an rpg right now, and getting into the guide is no problem, but it's getting back into the game which is a little cumbersome. In the in-game menu, you either have to hit down 3 times to cursor back up to Continue from Guide. Or hit up which I think is 4 times from Guide to get back to Continue. 

It's a small request, but I think one for who actually use the guide function will appreciate. When you have to get into the guide and back into the game you want to do it as quickly as possible. And if you were to move Guide right under Continue, you'll only have to press up once to get back into the game. 

I'm terrible at explaining things. If you need me to elaborate I will. 

Thanks for a great cfw!

**Comment by goweiwen** [comment]
That's a great suggestion.

Here's my workflow for using the guide, let me know if this works for you?

1. Press menu to open the ingame menu
2. Select guide
3. Press menu to close the ingame menu (you don't need to back out to hit continue)
4. When I press menu to open it up again, the guide should come back up.

**Comment by h8uthemost** [comment]
Sorry about the late reply. But that's sounds perfect!

Thank you for looking into this for me. For  Allium
