### ISSUE TITLE
Screen doesn´t turn off on suspend (MMP)

### ISSUE THREAD

**Issue by Oberworld** [goweiwen/Allium#58]
When I suspend the console, the screen goes black but it's clearly turned on. I have a miyoo mini plus.
I think this behavior represents a significant drain on the battery.
Also when I connect the charger, the screen has the same behavior, after the logo the screen goes black but remains on while charging.

I hope this problem has a simple solution.
All the best.

**Comment by tomh79** [comment]
Don't know about the suspend state. But while charging you can simply power the device off (long press power button) and the screen should turn off.

**Comment by Oberworld** [comment]
Thanks, it works for the charging process. Good tip. I didn't try that before.
I hope the suspend state can be fixed.

Regards.

**Comment by goweiwen** [comment]
Unfortunately, this device does not support a low-power suspend/sleep mode. We suspend RetroArch and turn off the display in suspend mode, and the device will automatically turn itself off after 5 minutes of idle.

**Comment by Oberworld** [comment]
Thanks for your answer.
The device boots quickly so I can live doing shutdown instead of suspend.
I think I can close this issue.
Regards.
