### ISSUE TITLE
Retroarch menu reacts awkwardly

### ISSUE THREAD

**Issue by josegonzalez** [goweiwen/Allium#6]
Very often, when I open the retroarch in-game settings, I see the following behavior:

- first time launch within a game: the screen goes black, and I have to press menu again to get to the main Allium screen, select the rom, play it, and then try again to get to the settings (it works this time)
- very frequently: the allium in-game menu flashes on top of the retroarch settings, which is distracting and quite buggy
- often: the retroarch settings either freeze or crash, though I can go back to the main allium menu and then get back to my game

This is with Allium v0.20.1 (I haven't upgraded to the latest release).

Not sure if there is any sort of debugging info I can get, though I'm happy to try and get a screen recording (not sure if the camera refresh rate will work) if you need it.

**Comment by goweiwen** [comment]
This might be a bug introduced in v0.20.1 and fixed in the next update. Let me know if you still face it when you update, together with any steps required to reproduce it.

**Comment by goweiwen** [comment]
Just found an issue related to this, where the RA menu overlaps the Allium menu when you try to open the menu in the RA menu. Will be fixed in the next update.

**Comment by josegonzalez** [comment]
So this got slightly better - I can get into the settings menu without it flashing - but once I try to move around, the menu "freezes". I can press the menu button again to get into the game, but then the Allium menu will flash on top of the game and I have to essentially exit the game and get back in before the UI gets together.
