### ISSUE TITLE
Question regarding the new motherboard revision and RTC

### ISSUE THREAD

**Issue by DovahSan** [goweiwen/Allium#68]
Hello, now that there's a new motherboard revision(manufactored in 2024,has RTC) out there I would like to know if there is any workaround or code needed to make the RTC work in the firmware as shown in this [post](https://www.reddit.com/r/MiyooMini/comments/1ceibjj/rtc_on_the_miyoo_mini_stepbystep_guide/) on reddit, im planning to get a new miyoo revision and since a like allium a lot, i would like to know if rtc is supported on the cfw.

**Comment by goweiwen** [comment]
It should automatically detect that the date is not resetting automatically, but I haven't tested it with a RTC-enabled device.

I actually added a clock widget in the status bar when testing this feature, but disabled it after. There's no way to enable the clock widget in the config as of right now.
