### ISSUE TITLE
Feature request: Toggle disable idle sleep

### ISSUE THREAD

**Issue by Pobega** [goweiwen/Allium#69]
https://github.com/goweiwen/Allium/commit/77f0b0429e5fe9a0529b9671288040b804790bc4 adds a hardcoded 5 minute sleep timer. In general this is great, but when transferring large files over FTP it causes me to have to constantly keep the device awake or lose the entire transfer.

A setting to disable idle sleep completely would be great for transferring files.

**Comment by goweiwen** [comment]
Good idea. I think Onion uses a file in `/tmp` to indicate that auto sleep should be disabled so the device doesn't go to sleep when using certain apps (like FFPlay). We can add something like this along with a toggle in the settings.

**Comment by goweiwen** [comment]
https://github.com/goweiwen/Allium/commit/325df6d09db05fa0fac25657ea33e2d29d506be7 adds two new settings that should help with this:
1. disable auto sleep when charging
2. adjust auto sleep duration (or disable)
