### ISSUE TITLE
Retroachievements Missing

### ISSUE THREAD

**Issue by hartleyshc** [goweiwen/Allium#73]
Retroachievements are missing from the latest 0.25.0 release. 

Setting is enabled in the User Interface settings. However the option is not visible in the Settings menu. 

Tried enabling and disabling in User Interface settings. Still not visible. 

Downgraded to previous version, enabled and signed into Retroachievements. Did an inplace upgrade to 0.25.0 version with the settings enabled. Lost functionality after upgrading to 0.25.0.

**Comment by goweiwen** [comment]
Thanks for reporting this. I think networking might have been accidentally disabled. I'll take a look and fix it.

**Comment by goweiwen** [comment]
Fixed in 655a3997560a91427da4cb09774701427779841b
