### ISSUE TITLE
Huge request - A30 version

### ISSUE THREAD

**Issue by h8uthemost** [goweiwen/Allium#77]
Any chance on a version for the A30 in the future? I've been using Allium for about a year and switching to another device without Allium is a little off-putting.

I'm using MinUI on it,  and I do love that cfw. I use it on my rg35xx. But I'm missing RetroArch and a guide feature and so many other things. So I was just wondering if this was in future plans 🙂

Thanks for reading

Edit: Also someone on Reddit was asking if Allium had the ability to trade Pokemon. Does it? I can't find a definitive answer in my searches

**Comment by goweiwen** [comment]
Allium relies on the RetroArch port built by the community for some features related to the in-game menu.

From what I understand (which is news from a couple of months ago), the A30 doesn't have its own open source RetroArch build yet.

I own one myself, so I would try to get Allium on it if this blocker is removed.
