### ISSUE TITLE
GBAOffset filter out of date, causes issues with some Onion overlays

### ISSUE THREAD

**Issue by Pobega** [goweiwen/Allium#78]
From what I can tell the GBAOffset filter needs to be one pixel higher, and the Perfect_GBA overlay has been updated to be one pixel shorter (https://github.com/OnionUI/Onion/pull/1537).

After putting all of these files from Onion onto my Allium install I now have a working GBA overlay. I'm not sure what method you use for updating these from Onion, but if it's not automatic I can throw up a PR bringing in these specific files -- just let me know.

* https://github.com/OnionUI/Onion/tree/7dfc008b851398dcfe57819519efe5f958c77f65/static/build/RetroArch/.retroarch/filters/video/GBA/Filter%20for%20overlays
* https://github.com/OnionUI/Onion/tree/7dfc008b851398dcfe57819519efe5f958c77f65/static/build/RetroArch/.retroarch/overlay/GBA/Perfect_GBA(read-instructions)

**Comment by Pobega** [comment]
I realize now that I actually added the Perfect_GBA overlay myself from Onion, I thought it was here already. Should I open a PR to add this overlay/filter to Allium?

**Comment by goweiwen** [comment]
I don't have any workflow for updating the overlays. Please go ahead with the PR if you have time, it would help a lot.
