### ISSUE TITLE
Web UI for uploading games

### ISSUE THREAD

**Issue by josegonzalez** [goweiwen/Allium#9]
It would be awesome to be able to upload games through a web ui. OnionOS allows this via a custom app, and this makes the process of adding games much simpler for those of us who have just cut our nails and can't get the SD card out :D

**Comment by josegonzalez** [comment]
A note for me from @goweiwen:

> onion's web browser works with some modifications, but if you want to try and implement an app you can try to add this: https://github.com/sigoden/dufs

>it should be in Apps (not App like Onion), in a directory ending with .pak, and have a launch.sh or config.json
> config.json's format is same as Onion's
> if no config, then launch.sh will be used

> to compile for miyoomini, you need to use Cross with the target set like this:
> cross build --target=arm-unknown-linux-gnueabihf

**Comment by goweiwen** [comment]
This is now implemented in 46ac79f36017af5735098c8195f5c4c27ca539d9as a setting in the Wi-Fi menu. The web server runs on port 80, so you should be able to access it by just typing the IP address in your URL bar.
